#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

alembic upgrade head
# Refer to app/app/ directory for FastAPI application instance
uvicorn app.main:app --reload --reload-dir app --host 0.0.0.0