#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A app.celery_app.celery inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

# must install flower to use the flower option with celery
celery flower \
  --app=app.celery_app.celery \
  --broker="${CELERY_BROKER_URL}"
